server:
  port: 8081

spring:
  application:
       name: patient-service
  cloud:
    inetutils:
      preferred-networks:
        - 127

  data:
    mongodb:
       host: mongo
       port: 27017
       database: healthcare_db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: patient-service
