version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: appointment-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: appt_admin
      POSTGRES_PASSWORD: appt_pass
      POSTGRES_DB: appointment_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



